// index.js
const { Agent } = require('./src/agent/Agent');
const { Tool } = require('./src/tools/adapters/Tool');
const { MCPDiscoveryLoader } = require('./src/tools/adapters/MCPDiscoveryLoader');
const { Memory } = require('./src/agent/Memory'); 
const { BaseLayerStore } = require('./src/agent/memory/BaseLayerStore');
const { InMemoryLayerStore } = require('./src/agent/memory/InMemoryLayerStore');
const { FileLayerStore } = require('./src/agent/memory/FileLayerStore');
const { OpenAIAdapter } = require('./src/llm/OpenAi');
const { GeminiAdapter } = require('./src/llm/Gemini');
const { HFAdapter } = require('./src/llm/HuggingFace');
const { AnthropicAdapter } = require('./src/llm/Anthropic');
const { DeepSeekAdapter } = require('./src/llm/DeepSeek');
const { FallbackRouter } = require('./src/llm/FallbackRouter');
const { PineconeManager } = require('./src/db/PineconeManager');
const { LocalVectorStore } = require('./src/db/LocalVectorStore');
const { RAG } = require('./src/rag/RAG');
const { BaseRetriever } = require('./src/rag/retrievers/BaseRetriever');
const { VectorStoreRetriever } = require('./src/rag/retrievers/VectorStoreRetriever');
const { Task } = require('./src/workflow/Task');
const { Orchestrator } = require('./src/workflow/Orchestrator');
const { RetryManager } = require('./src/utils');
const { encodeBase64 } = require('./src/utils');
const { chunkText } = require('./src/utils');
const { repairJsonOutput } = require('./src/utils');
const { MCPTool } = require('./src/mcp/MCPTool');
const { MCPClient } = require('./src/mcp/MCPClient');
const { OpenAPILoader } = require('./src/api/OpenAPILoader');
const { ApiLoader } = require('./src/api/ApiLoader');
const {
  CritiqueProtocol,
  CritiqueSchemaRegistry,
  TrustRegistry,
  DisagreementResolver,
  CoordinationLoop,
  DecompositionAdvisor,
} = require('./src/coordination');
const {
  Run,
  RunInspector,
  RunTreeInspector,
  IncidentDebugger,
  BranchQualityAnalyzer,
  DistributedRecoveryPlanner,
  DistributedRecoveryRunner,
  TraceDiffer,
  TraceCorrelation,
  TraceSerializer,
  ExecutionIdentity,
  EvidenceGraph,
  EvalHarness,
  LearningLoop,
  PolicyTuningAdvisor,
  VerifierEnsemble,
  ConfidencePolicy,
  AdaptiveRetryPolicy,
  HistoricalRoutingAdvisor,
  AdaptiveDecisionLedger,
  AdaptiveGovernanceGate,
  GovernanceHooks,
  WebhookGovernanceAdapter,
  ExtensionHost,
  StorageBackendRegistry,
  ApprovalInbox,
  BackgroundJobScheduler,
  DelegationRuntime,
  PlanningRuntime,
  ToolPolicy,
  EventBus,
  ConsoleDebugSink,
  FileAuditSink,
  WebhookEventSink,
  RuntimeEventRedactor,
  DistributedRunEnvelope,
  BaseRunStore,
  BaseJobStore,
  InMemoryRunStore,
  FileRunStore,
  InMemoryJobStore,
  FileJobStore,
  BaseEnvironmentAdapter,
  BrowserEnvironmentAdapter,
  ShellEnvironmentAdapter,
  ApiEnvironmentAdapter,
  QueueEnvironmentAdapter,
  FileEnvironmentAdapter,
  Workflow,
  WorkflowStep,
  ExecutionGraph,
  DelegationContract,
  AgentWorkflowStep,
  WorkflowRunner,
} = require('./src/runtime');
const {
  AgentError,
  AdapterCapabilityError,
  InvalidToolCallError,
  ToolNotFoundError,
  ToolExecutionError,
  ToolPolicyError,
  ApprovalRequiredError,
  RunNotFoundError,
  RunPausedError,
  RunCancelledError,
} = require('./src/errors');

module.exports = {
  Agent,
  Tool,
  Memory,
  BaseLayerStore,
  InMemoryLayerStore,
  FileLayerStore,
  OpenAIAdapter,
  GeminiAdapter,
  AnthropicAdapter,
  HFAdapter,
  DeepSeekAdapter,
  FallbackRouter,
  PineconeManager,
  LocalVectorStore,
  RAG,
  BaseRetriever,
  VectorStoreRetriever,
  Task,
  Orchestrator,
  RetryManager,
  chunkText,
  repairJsonOutput,
  encodeBase64,
  MCPTool,
  MCPClient,
  OpenAPILoader,
  MCPDiscoveryLoader,
  ApiLoader,
  CritiqueProtocol,
  CritiqueSchemaRegistry,
  TrustRegistry,
  DisagreementResolver,
  CoordinationLoop,
  DecompositionAdvisor,
  Run,
  RunInspector,
  RunTreeInspector,
  IncidentDebugger,
  BranchQualityAnalyzer,
  DistributedRecoveryPlanner,
  DistributedRecoveryRunner,
  TraceDiffer,
  TraceCorrelation,
  TraceSerializer,
  ExecutionIdentity,
  EvidenceGraph,
  EvalHarness,
  LearningLoop,
  PolicyTuningAdvisor,
  VerifierEnsemble,
  ConfidencePolicy,
  AdaptiveRetryPolicy,
  HistoricalRoutingAdvisor,
  AdaptiveDecisionLedger,
  AdaptiveGovernanceGate,
  GovernanceHooks,
  WebhookGovernanceAdapter,
  ExtensionHost,
  StorageBackendRegistry,
  ApprovalInbox,
  BackgroundJobScheduler,
  DelegationRuntime,
  PlanningRuntime,
  ToolPolicy,
  EventBus,
  ConsoleDebugSink,
  FileAuditSink,
  WebhookEventSink,
  RuntimeEventRedactor,
  DistributedRunEnvelope,
  BaseRunStore,
  BaseJobStore,
  InMemoryRunStore,
  FileRunStore,
  InMemoryJobStore,
  FileJobStore,
  BaseEnvironmentAdapter,
  BrowserEnvironmentAdapter,
  ShellEnvironmentAdapter,
  ApiEnvironmentAdapter,
  QueueEnvironmentAdapter,
  FileEnvironmentAdapter,
  Workflow,
  WorkflowStep,
  ExecutionGraph,
  DelegationContract,
  AgentWorkflowStep,
  WorkflowRunner,
  AgentError,
  AdapterCapabilityError,
  InvalidToolCallError,
  ToolNotFoundError,
  ToolExecutionError,
  ToolPolicyError,
  ApprovalRequiredError,
  RunNotFoundError,
  RunPausedError,
  RunCancelledError,
};
